### ISSUE TITLE
thank you your plugin

### ISSUE THREAD

**Issue by liuyehua** [juliuscanute/qr_code_scanner#1]
Your plugin very nice，but I found when I exit the cameraPage but the console always print "E/Camera-JNI( 9959): copyAndPost: off=0, size=3110400 msg=10" , it really no Problem? Have any method to dispose the camera when I leave the page?

**Comment by liuyehua** [comment]
another problem is when the camera outer widget change size such as width or height changed, the camera will be in black screen....

**Comment by luis901101** [comment]
I am facing the same problem, the camera stays on when I leave the Route containing the QRView(). It would be nice if the resources acquired by the QRView() could be released.

PS: I consider this plugin the best choice for (qr/barcode) scanning, due to the possibility of embedded scanner in a ViewWidget
