### ISSUE TITLE
[iOS] Can not scan at the first time after install app

### ISSUE THREAD

**Issue by nambv** [juliuscanute/qr_code_scanner#129]
@juliuscanute after installed app, I try to scan the barcode but it's not working, after I close app and open again, it works. Seem cannot scan at the first time, can you take a look.

only happen in iOS, Android is working fine

**Comment by pedroafonsouza** [comment]
@nambv do you have the log error?

**Comment by eddiesTime** [comment]
@nambv, the behavior is related to #127. I've run into the same problem that the scanner did not work as intended on the first start of the app. The intentional space configured for the scanner overlay was ignored and instead used space that it was not supposed to use. I've added a screenshot so you can see for yourself. The overlay is not supposed to be rendered outside of the dialog. Unfortunately, it did render outside of the dialog to the bottom and right.

![IMG_9927](https://user-images.githubusercontent.com/33376523/97970609-0cc48a00-1dc2-11eb-8d81-1f21016a25ba.PNG)


After adding a request for permissions with [permission_handler](https://pub.dev/packages/permission_handler) before creating the overlay screen, the initial build of the scanner works as intended and the scanner works too.

**Comment by juliansteenbakker** [comment]
Can you please test again with 0.1.0. This version fixes some dimension issues on iOS. Please comment if this issue still persists.
