### ISSUE TITLE
iPad Mini "Lost connection to device" no errors

### ISSUE THREAD

**Issue by lextoc** [juliuscanute/qr_code_scanner#171]
I've installed this package and created a new screen in which it's used. An iPad Mini is connected to my Xcode so I can develop on it. As soon as I go to the screen with the `qr_code_scanner` widget the app closes and a message is shown in logs "Lost connection to device" without any error. Any ideas what this might be?

**Comment by juliansteenbakker** [comment]
Can you please provide which iPad it is, and which iOS it's running? Also it would be great if you can post the output of `flutter doctor -v`.

**Comment by lextoc** [comment]
It's an iPad mini 2 running on `12.4.9`. This is the output of `flutter doctor -v`:

```
➜  visitor-app git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale en-BE)
    • Flutter version 1.22.4 at /Users/alexanderclaes/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /usr/local/share/android-sdk
      but Android SDK not found at this location.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.10.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPad van Alexander (mobile) • d220bdc69e5a45c497074b86fcdeecdbd1596424 • ios • iOS 12.4.9

! Doctor found issues in 2 categories.
```

**Comment by juliansteenbakker** [comment]
When i run the plugin without providing permission i get the same behaviour. Xcode gave the following error 

`2020-12-11 10:20:38.529413+0100 Runner[472:87289] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.`

Please make sure you have added the permission to your `info.plist` file.
`<key>NSCameraUsageDescription</key>`
`<string>This app needs camera access to scan QR codes</string>`

**Comment by lextoc** [comment]
This solved my issue, thank you so much!

**Comment by lextoc** [comment]
Small side note: if you are debugging in VS Code like me, check Xcode as well as the logs contain more info than those in VS Code. Just checked and your message was also in there. 🤦‍♂️
