### ISSUE TITLE
The method 'updateDimensions' isn't defined for the type 'QRViewController

### ISSUE THREAD

**Issue by w461** [juliuscanute/qr_code_scanner#178]
I guess it's me, but I have no idea what I have done wrong. I copied `Widget _buildQrView() {}` into my State class but I get the above error for the line `Future.microtask(() => controller?.updateDimensions(qrKey));`

All variables are also declared in the class.

If I enter `controller.` I do see several method suggestions, however, updateDimensions is none of them.

Any idea why this seems to work for everyone but me?! Cheers

**Comment by juliansteenbakker** [comment]
Which version are you using? That method is only available on 0.1.0.

**Comment by w461** [comment]
With the latest. Maybe you could update the examples given here, then. Both still state updateDimensions. Is there any other snippet how to implement qr_code_scanner?

**Comment by w461** [comment]
I just checked the code drops here. And while you just dropped a change with the remark `juliansteenbakker Updated Flutter min sdk of example to match plugin. Updated README.md`, `qr_code_scanner/example/lib/main.dart` still shows updateDimensions. Maybe you uploaded the old documents by accident?

**Comment by juliansteenbakker** [comment]
The docs are updated according to version 0.1.0. [As you can see here](https://github.com/juliuscanute/qr_code_scanner/blob/d70ded0bb0e79ee0670e5511b55f91c3fef23244/lib/src/qr_code_scanner.dart#L145), the method updateDimensions is introduced in 0.1.0 and fixes rotation issues on iOS. If you have 0.1.0 in your pubspec.yaml please run `flutter pub cache repair` in order to redownload all packages.

**Comment by w461** [comment]
Applologies, I included qr_code_scanner yesterday, so I thought I would have the latest version. Now that I entered 0.1.0 in yaml, it works. Thanks!
