### ISSUE TITLE
Android 'CameraInfo' is deprecated.

### ISSUE THREAD

**Issue by MuthuSubramaniam** [juliuscanute/qr_code_scanner#25]
In QRView class we are using CameraInfo. But CameraInfo is deprecated. Can you look into this solve the updated one! Thanks!

**Comment by juliansteenbakker** [comment]
Until the android library gets updated we need to use this. See https://github.com/journeyapps/zxing-android-embedded/blob/8df0cb554a8e9f236273ca7ce10d4c7e6e814a9d/zxing-android-embedded/src/com/journeyapps/barcodescanner/camera/CameraManager.java#L350

Another solution would be to switch from library since zxing isn't actively maintained. This is discussed at #176.
