### ISSUE TITLE
[android] why is >v20 is requied

### ISSUE THREAD

**Issue by daadu** [juliuscanute/qr_code_scanner#261]
**Is your feature request related to a problem? Please describe.**
I like this plugin and would want to know why is this a requirement? My app supports min. 18, I don't want to upgrade it just for this plugin.

**Describe the solution you'd like**
Is it because of "platform view"? in that case providing a fallback mechanism, with "native-only activity" can be used.

**Comment by juliansteenbakker** [comment]
This is indeed because of the platform-view which only supports sdk 20 and up. I've tried implementing a hybrid view which supports sdk 19 however this did not work. I am not familiar with "native-only activity". Right now i am working on a version that does not need a platform view and native frameworks which will change the min sdk version so i am closing this issue for now.

**Comment by daadu** [comment]
@juliansteenbakker Can you keep this issue open, till the version is implemented or released?

**Comment by daadu** [comment]
@juliansteenbakker  "native-only activity" meant something that you are working on!

**Comment by juliansteenbakker** [comment]
I will track this in the issue that discusses the new framework (#176) because we can't apply this to the current framework.
