### ISSUE TITLE
App crashes on android release mode[BUG] 

### ISSUE THREAD

**Issue by CleverBoy53** [juliuscanute/qr_code_scanner#282]
**Describe the bug**
When i use the app on debug mode there is no problem but when i try to use it on release mode, when i open the page which has QRView after i apply the camera permission it crashes. Error from logcat;

    java.lang.RuntimeException: java.lang.NoSuchMethodException: b.c.c.e.values []
        at java.lang.Enum.enumValues(Enum.java:270)
        at java.lang.Enum.access$000(Enum.java:61)
        at java.lang.Enum$1.create(Enum.java:277)
        at java.lang.Enum$1.create(Enum.java:275)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
        at java.util.EnumMap.<init>(EnumMap.java:138)
        at com.journeyapps.barcodescanner.A.a(Unknown Source:4)
        at com.journeyapps.barcodescanner.BarcodeView.E(:2)
        at com.journeyapps.barcodescanner.BarcodeView.I(Unknown Source:21)
        at com.journeyapps.barcodescanner.BarcodeView.w(Unknown Source:0)
        at com.journeyapps.barcodescanner.q.A(Unknown Source:28)
        at com.journeyapps.barcodescanner.q.B(Unknown Source:48)
        at com.journeyapps.barcodescanner.q.d(:5)
        at com.journeyapps.barcodescanner.m.handleMessage(Unknown Source:13)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Flutter information**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.844], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.0)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.1)
[√] Connected device (4 available)

• No issues found!

**Device**
 - Device: [s7 edge]
 - OS: [android 10]

**Comment by burhanhaq** [comment]
Experiencing exactly same issue.
Devices: S10e and S20
Android: 10

**Comment by burhanhaq** [comment]
Here is the bug report for 0.3.5

E/AndroidRuntime(21192): FATAL EXCEPTION: main
E/AndroidRuntime(21192): Process: io.liquidstar, PID: 21192
E/AndroidRuntime(21192): java.lang.RuntimeException: java.lang.NoSuchMethodException: b.c.b.e.values []
E/AndroidRuntime(21192):        at java.lang.Enum.enumValues(Enum.java:270)
E/AndroidRuntime(21192):        at java.lang.Enum.access$000(Enum.java:61)
E/AndroidRuntime(21192):        at java.lang.Enum$1.create(Enum.java:277)
E/AndroidRuntime(21192):        at java.lang.Enum$1.create(Enum.java:275)
E/AndroidRuntime(21192):        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(21192):        at java.lang.Enum.getSharedConstants(Enum.java:289)
E/AndroidRuntime(21192):        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
E/AndroidRuntime(21192):        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
E/AndroidRuntime(21192):        at java.util.EnumMap.<init>(EnumMap.java:138)
E/AndroidRuntime(21192):        at com.journeyapps.barcodescanner.A.a(Unknown Source:4)
E/AndroidRuntime(21192):        at com.journeyapps.barcodescanner.BarcodeView.E(:2)
E/AndroidRuntime(21192):        at com.journeyapps.barcodescanner.BarcodeView.I(Unknown Source:21)
E/AndroidRuntime(21192):        at com.journeyapps.barcodescanner.BarcodeView.w(Unknown Source:0)
E/AndroidRuntime(21192):        at com.journeyapps.barcodescanner.q.A(Unknown Source:28)
E/AndroidRuntime(21192):        at com.journeyapps.barcodescanner.q.B(Unknown Source:48)
E/AndroidRuntime(21192):        at com.journeyapps.barcodescanner.q.d(:5)
E/AndroidRuntime(21192):        at com.journeyapps.barcodescanner.m.handleMessage(Unknown Source:13)
E/AndroidRuntime(21192):        at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(21192):        at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(21192):        at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime(21192):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21192):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(21192):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E/AndroidRuntime(21192): Caused by: java.lang.NoSuchMethodException: b.c.b.e.values []
E/AndroidRuntime(21192):        at java.lang.Class.getMethod(Class.java:2072)
E/AndroidRuntime(21192):        at java.lang.Class.getDeclaredMethod(Class.java:2050)
E/AndroidRuntime(21192):        at java.lang.Enum.enumValues(Enum.java:267)
E/AndroidRuntime(21192):        ... 22 more

**Comment by mejdi14** [comment]
if anyone facing the same problem you can find the solution here :
https://stackoverflow.com/questions/54847976/java-lang-assertionerror-impossible-caused-by-java-lang-nosuchmethodexception

**Comment by CleverBoy53** [comment]
> if anyone facing the same problem you can find the solution here :
> https://stackoverflow.com/questions/54847976/java-lang-assertionerror-impossible-caused-by-java-lang-nosuchmethodexception

this solution worked for me. thank you

**Comment by CleverBoy53** [comment]
> if anyone facing the same problem you can find the solution here :
> https://stackoverflow.com/questions/54847976/java-lang-assertionerror-impossible-caused-by-java-lang-nosuchmethodexception

this solution worked for me. thank you

**Comment by burhanhaq** [comment]
> if anyone facing the same problem you can find the solution here :
> https://stackoverflow.com/questions/54847976/java-lang-assertionerror-impossible-caused-by-java-lang-nosuchmethodexception

Works for me as well :D

**Comment by liasica** [comment]
> if anyone facing the same problem you can find the solution here :
> https://stackoverflow.com/questions/54847976/java-lang-assertionerror-impossible-caused-by-java-lang-nosuchmethodexception

Works good for me, thanks.
