### ISSUE TITLE
Other Barcode Formats

### ISSUE THREAD

**Issue by Giles-W** [juliuscanute/qr_code_scanner#48]
I really like your scanner and the fact that I can customize the widget that it displays in. Nice work.

I am hoping that there is a way to use it also scan other types of 2D and even 1D barcodes as well? In particular, I need to scan PDF417 and Aztec barcodes, as well as 3 of 9 (code 39).

I was really hoping that being based on the ZXing libraries, this would be possible.

Please tell me I just need to change the value of the `qrKey` or something equally simple. ;)

Thank you.

**Comment by luis901101** [comment]
As you indicates this plugin uses ZXing libraries for code scanning which in turn defines the entire list of formats as default formats to scan:
this is the list:

public enum BarcodeFormat {

  /** Aztec 2D barcode format. */
  AZTEC,

  /** CODABAR 1D format. */
  CODABAR,

  /** Code 39 1D format. */
  CODE_39,

  /** Code 93 1D format. */
  CODE_93,

  /** Code 128 1D format. */
  CODE_128,

  /** Data Matrix 2D barcode format. */
  DATA_MATRIX,

  /** EAN-8 1D format. */
  EAN_8,

  /** EAN-13 1D format. */
  EAN_13,

  /** ITF (Interleaved Two of Five) 1D format. */
  ITF,

  /** MaxiCode 2D barcode format. */
  MAXICODE,

  /** PDF417 format. */
  PDF_417,

  /** QR Code 2D barcode format. */
  QR_CODE,

  /** RSS 14 */
  RSS_14,

  /** RSS EXPANDED */
  RSS_EXPANDED,

  /** UPC-A 1D format. */
  UPC_A,

  /** UPC-E 1D format. */
  UPC_E,

  /** UPC/EAN extension format. Not a stand-alone format. */
  UPC_EAN_EXTENSION

}

**Comment by Giles-W** [comment]
At this point, my app with your plugin is only able to scan QR codes. I have tried to scan AZTEC, PDF417, CODE_39, EAN_13 and while my sample barcodes read just fine using the ZXing sample app, they don't scan with your plugin.

If I read your response correctly, you're saying that they are enabled by default. So I'll have to use something else.

**Comment by luis901101** [comment]
I'm not the developer of this plugin but I have been using it for a while. What I am telling you is that for Android the ZXing library by default includes all formats... this plugin uses the ZXing library without any modification then you should be able to scan any of the accepted code from the list I shared above. I just have tested in https://barcode.tec-it.com/en/PDF417?data=qweqwe and the app scans it perfectly... I'm using the v0.0.12...
I recommend you to try with a device with a good camera hardware because there are some codes that are difficult to scan... the QRCode is the most easy code to scan that's why you get the sensation that the plugin doesn't scan any other.

**Comment by dspicher** [comment]
As per the comment above the formats are acutally all supported.
Please post a full example if you keep running into issues.
